PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?entity ?property ?value WHERE {
 {
  VALUES ?property {
    owl:equivalentClass
    rdfs:subClassOf
    owl:disjointWith
  }
  ?entity owl:deprecated true .
  ?value ?property ?entity .
 }
 UNION
 {
   VALUES ?property {
     owl:equivalentClass
     rdfs:subClassOf
     owl:disjointWith
   }
  ?entity owl:deprecated true .
  ?entity ?property ?value .
 }
}
ORDER BY ?entity