prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?phenotype ?label ?description ?syn WHERE 
{
  ?phenotype rdfs:label ?label . 
	OPTIONAL
  { 
    ?phenotype <http://purl.obolibrary.org/obo/IAO_0000115> ?description .
  }
	OPTIONAL
  { 
    ?phenotype <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?syn .
  }
}
