SELECT DISTINCT ?term
WHERE {
  { ?s1 ?p1 ?term . }
  UNION
  { ?term ?p2 ?o2 . }
  FILTER(isIRI(?term) && (regex(str(?term), UCASE("hp_")) || regex(str(?term), "http://purl.obolibrary.org/obo/HP_") || regex(str(?term), "http://purl.obolibrary.org/obo/hp")))
}


