PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX replaced_by: <http://purl.obolibrary.org/obo/IAO_0100001>

SELECT ?cls WHERE {
	?cls a owl:Class
	FILTER NOT EXISTS {?cls rdfs:label ?lab}
	FILTER NOT EXISTS {?cls replaced_by: ?replCls}
        FILTER (!isBlank(?cls))
        FILTER ( regex(str(?cls), "^http://purl.obolibrary.org/obo/GO_"))
}
ORDER BY ?cls
