PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX replaced_by: <http://purl.obolibrary.org/obo/IAO_0100001>

SELECT ?cls WHERE {
	?cls a owl:Class
	FILTER NOT EXISTS { owl:deprecated true . }
	FILTER NOT EXISTS {?cls rdfs:subClassOf* <http://purl.obolibrary.org/obo/HP_0000001>}
        FILTER (!isBlank(?cls))
        FILTER ( STRSTARTS(str(?cls), "^http://purl.obolibrary.org/obo/HP_"))
}
ORDER BY ?cls
