prefix xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?term ?label ?child ?child_label
WHERE {
  ?child rdfs:subClassOf ?term .
	?term rdfs:label ?label .
	?child rdfs:label ?child_label .
}
