license: "https://creativecommons.org/publicdomain/zero/1.0/"
mapping_set_id: http://purl.obolibrary.org/obo/hp/mappings/hp-snomed
curie_map:
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  owl: "http://www.w3.org/2002/07/owl#"
  SNOMED: "http://snomed.info/id/"
  HP: http://purl.obolibrary.org/obo/HP_
  orcid: "https://orcid.org/"
