inverse_predicate_map:
  skos:closeMatch: skos:closeMatch
  skos:relatedMatch: skos:relatedMatch
  skos:exactMatch: skos:exactMatch
  skos:narrowMatch: skos:broadMatch
  skos:broadMatch: skos:narrowMatch
  semapv:crossSpeciesExactMatch: semapv:crossSpeciesExactMatch
  semapv:crossSpeciesNarrowMatch: semapv:crossSpeciesBroadMatch
  semapv:crossSpeciesBroadMatch: semapv:crossSpeciesNarrowMatch
  semapv:crossSpeciesCloseMatch: semapv:crossSpeciesCloseMatch
  owl:equivalentClass: owl:equivalentClass
  owl:sameAs: owl:sameAs
  rdfs:subClassOf: sssom:superClassOf
  sssom:superClassOf: rdfs:subClassOf
